CREATE TABLE AWS_TOKENS 
(
  TOK_ID NUMBER(38) NOT NULL 
, HASH VARCHAR2(256) NOT NULL 
, CREATION_DATE TIMESTAMP NOT NULL 
, EXPIRY_DATE TIMESTAMP NOT NULL 
, CONSTRAINT AWS_TOKENS_PK PRIMARY KEY 
  (
    TOK_ID 
  )
  ENABLE 
);
