CREATE TABLE AWS_ACCIDENT_INFO 
(
  ID NUMBER(38) NOT NULL 
, LOC_ID NUMBER(38) NOT NULL 
, CAUSE VARCHAR2(100) 
, CARS_INVOLVED INTEGER 
, VICTIMS NUMBER(3) 
, CONSTRAINT AWS_ACCIDENT_INFO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE AWS_ACCIDENT_INFO
ADD CONSTRAINT AWS_ACCIDENT_INFO_FK1 FOREIGN KEY
(
  LOC_ID 
)
REFERENCES AWS_COORDINATES
(
  ID 
)
ON DELETE CASCADE ENABLE;
