CREATE TABLE AWS_COORDINATES 
(
  ID INTEGER NOT NULL 
, COORD MDSYS.SDO_GEOMETRY NOT NULL 
, TIMESTAMP TIMESTAMP WITH LOCAL TIME ZONE NOT NULL 
, HITS INTEGER DEFAULT 1 
, CONSTRAINT AWS_COORDINATES_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);
