INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) 
   VALUES ('AWS_COORDINATES', 'COORD', 
   SDO_DIM_ARRAY 
     (SDO_DIM_ELEMENT('LONG', -180.0, 180.0, 100), 
     SDO_DIM_ELEMENT('LAT', -90.0, 90.0, 100)), 
   8307);